sensor:
####################################
## Apparent Current Configuration ##
## Ensure the right voltage       ##
####################################
## needs to be calculated from the two sides of apparent current, which is what is measured directly off of the ct_clamps
    # These have to be added using the root sum of squares method, the lambda below chooses between 2 or 3 phase based on configuration
  - &template_apparentcurrent
    platform: template
    id: total_apparentcurrent
    lambda: |-
        float Ia = id(phase_a_apparentcurrent).state;
        float Ib = id(phase_b_apparentcurrent).state;
        float Ic = id(phase_c_apparentcurrent).state;
        float thetaA = id(phase_a_angle).state;
        float thetaB = id(phase_b_angle).state;
        float thetaC = id(phase_c_angle).state;
    
        bool disabled = "${ct_c.disable}";
    
        float total_current;
    
        if (disabled) {
            // Two-phase circuit
            float cosA = cos(thetaA);
            float sinA = sin(thetaA);
            float cosB = cos(thetaB);
            float sinB = sin(thetaB);
            total_current = sqrt(pow(Ia * cosA + Ib * cosB, 2) + pow(Ia * sinA + Ib * sinB, 2));
        } else {
            // Three-phase circuit
            float cosA = cos(thetaA);
            float sinA = sin(thetaA);
            float cosB = cos(thetaB);
            float sinB = sin(thetaB);
            float cosC = cos(thetaC);
            float sinC = sin(thetaC);
            total_current = sqrt(pow(Ia * cosA + Ib * cosB + Ic * cosC, 2) + pow(Ia * sinA + Ib * sinB + Ic * sinC, 2));
        }
        
        return total_current;

    update_interval: never
    device_class: current
    state_class: measurement
    unit_of_measurement: "A"
